-- ============================================================================
-- Seed: medications catalogue
-- ============================================================================
-- Source: WHO Model List of Essential Medicines, 24th list (2025).
--   https://www.who.int/publications/i/item/B09474
--   Licence: CC BY-NC-SA 3.0 IGO
--
-- 755 rows / 529 distinct medicines, one row per (name, dosage form),
-- extracted from the published list. `strengths` holds the formulation
-- strengths exactly as the WHO list prints them ('25 mg', '5 mg/mL in
-- 1 mL ampoule', '0.25 mg to 6.0 mg'), so selecting a medication can
-- offer its real strengths rather than making the doctor retype them.
--
-- Rows with a null `form` and no strengths are medicines the WHO list
-- names only as a therapeutic alternative to another entry (sertraline,
-- escitalopram, aripiprazole, lorazepam and similar). They are included
-- because they are commonly prescribed and should be findable; they
-- simply carry no formulation data of their own, so the UI will not
-- prefill a dosage for them.
--
-- This is a general medical catalogue, not a psychiatric one â€” the whole
-- WHO list is here, from anaesthetics to antiretrovirals.
--
-- Adapt freely: the WHO list is a model for national lists, not a
-- formulary. Delete what the clinic never prescribes and insert local
-- products as needed; free-text medication entry remains available in the
-- consultation form regardless.
--
-- Idempotent: ON CONFLICT targets medications_name_form_key.
-- ============================================================================

insert into public.medications (name, form, strengths, drug_class) values
  ('Abacavir', 'Tablet', array['300 mg (as sulfate)'], 'Antiretrovirals'),
  ('Abacavir + dolutegravir + lamivudine', 'Tablet (dispersible)', array['60 mg (as sulfate) + 5 mg + 30 mg'], 'Antiretrovirals'),
  ('Abacavir + lamivudine', 'Tablet (dispersible, scored)', array['120 mg (as sulfate) + 60 mg'], 'Antiretrovirals'),
  ('Abiraterone', 'Tablet', array['250 mg', '500 mg'], 'Hormones and antihormones'),
  ('Acamprosate calcium', 'Tablet', array['333 mg'], 'Medicines for alcohol use disorders'),
  ('Acenocoumarol', null, '{}', 'Medicines affecting coagulation'),
  ('Acetazolamide', 'Tablet', array['250 mg'], 'Miotics and antiglaucoma medicines'),
  ('Acetic acid', 'Solution (ear drops)', array['2%'], 'Ear, nose and throat medicines'),
  ('Acetylcysteine', 'Injection', array['200 mg/mL in 10 mL ampoule'], 'Specific'),
  ('Acetylsalicylic acid', 'Suppository', array['50 mg to 150 mg', '150 mg', '300 mg'], 'Non-opioids and non-steroidal anti-inflammatory medicines (NSAIMs)'),
  ('Acetylsalicylic acid', 'Tablet', array['100 mg to 500 mg', '300 mg to 500 mg', '100 mg', '75 mg to 500 mg'], 'Non-opioids and non-steroidal anti-inflammatory medicines (NSAIMs)'),
  ('Acetylsalicylic acid', 'Tablet (dispersible)', array['75 mg', '300 mg', '500 mg'], 'Non-opioids and non-steroidal anti-inflammatory medicines (NSAIMs)'),
  ('Aciclovir', 'Ointment', array['3% w/w'], 'Medicines for central nervous system infections'),
  ('Aciclovir', 'Oral liquid', array['200 mg/5 mL'], 'Medicines for central nervous system infections'),
  ('Aciclovir', 'Powder for solution for infusion', array['250 mg (as sodium dihydrate) in vial'], 'Medicines for central nervous system infections'),
  ('Aciclovir', 'Solution for infusion', array['25 mg/mL (as sodium) in vial'], 'Medicines for central nervous system infections'),
  ('Aciclovir', 'Tablet', array['200 mg'], 'Medicines for central nervous system infections'),
  ('Aclidinium', null, '{}', 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Afatinib', null, '{}', 'Targeted therapies'),
  ('Albendazole', 'Tablet (chewable, scored)', array['400 mg'], 'Intestinal anthelminthics'),
  ('Albendazole', 'Tablet (chewable)', array['200 mg'], 'Intestinal anthelminthics'),
  ('Alcohol based hand rub', 'Solution', array['containing ethanol 80% volume/volume', 'containing isopropyl alcohol 75% volume/volume'], 'Disinfectants'),
  ('All-trans retinoid acid (ATRA)', 'Capsule', array['10 mg'], 'Targeted therapies'),
  ('Allopurinol', 'Powder for injection', array['500 mg (as sodium) Tablet: 100 mg', '300 mg'], 'Supportive medicines'),
  ('Allopurinol', 'Tablet', array['100 mg'], 'Supportive medicines'),
  ('Alprostadil (prostaglandin E1)', 'Solution for injection', array['0.5 mg/mL in alcohol'], 'Medicines administered to the neonate [c]'),
  ('Alteplase', 'Powder for injection', array['10 mg', '20 mg', '50 mg in vial'], 'Thrombolytic medicines'),
  ('Amidotrizoate', 'Injection', array['140 mg to 420 mg iodine/mL (as sodium or meglumine salt) in 20 mL ampoule'], 'Radiocontrast media'),
  ('Amikacin', 'Injection', array['50 mg/mL (as sulfate)', '250 mg/mL (as sulfate) in 2 mL vial'], 'Access group antibiotics'),
  ('Amiloride', 'Tablet', array['5 mg (hydrochloride)'], 'Diuretics'),
  ('Amiodarone', 'Injection', array['50 mg/mL (hydrochloride) in 3 mL ampoule'], 'Antiarrhythmic medicines'),
  ('Amiodarone', 'Tablet', array['100 mg', '200 mg', '400 mg (hydrochloride)'], 'Antiarrhythmic medicines'),
  ('Amitriptyline', 'Oral liquid', array['25 mg/5 mL'], 'Medicines for other common symptoms in palliative care'),
  ('Amitriptyline', 'Tablet', array['10 mg', '25 mg', '75 mg', '75 mg (hydrochloride)'], 'Medicines for other common symptoms in palliative care'),
  ('Amodiaquine â€“ sulfadoxine + pyrimethamine', 'Co-packaged dispersible tablets', array['amodiaquine 75 mg (as hydrochloride) and sulfadoxine + pyrimethamine 250 mg + 12.5 mg'], 'Antimalarial medicines'),
  ('Amoxicillin', 'Powder for injection', array['250 mg', '500 mg', '1 g (as sodium) in vial'], 'Medicines for central nervous system infections'),
  ('Amoxicillin', 'Powder for oral liquid', array['125 mg/5 mL', '250 mg/5 mL (as trihydrate)'], 'Medicines for central nervous system infections'),
  ('Amoxicillin', 'Solid oral dosage form', array['250 mg', '500 mg (as trihydrate)', '500 mg', '1 g (as trihydrate)'], 'Medicines for central nervous system infections'),
  ('Amoxicillin', 'Tablet (dispersible, scored)', array['250 mg', '500 mg (as trihydrate)'], 'Medicines for central nervous system infections'),
  ('Amoxicillin + clavulanic acid', 'Powder for injection', array['500 mg (as sodium) + 100 mg (as potassium salt)', '1000 mg (as sodium) + 200 mg (as potassium salt) in vial'], 'Access group antibiotics'),
  ('Amoxicillin + clavulanic acid', 'Powder for oral liquid', array['125 mg (as trihydrate) + 31.25 mg (as potassium salt)/5 mL', '250 mg (as trihydrate) + 62.5 mg (as potassium salt)/5 mL'], 'Access group antibiotics'),
  ('Amoxicillin + clavulanic acid', 'Tablet', array['500 mg (as trihydrate) + 125 mg (as potassium salt)', '875 mg (as trihydrate) + 125 mg (as potassium salt)'], 'Access group antibiotics'),
  ('Amoxicillin + clavulanic acid', 'Tablet (dispersible)', array['200 mg (as trihydrate) + 28.5 mg (as potassium salt)', '250 mg (as trihydrate) + 62.5 mg (as potassium salt)'], 'Access group antibiotics'),
  ('Amphotericin B', 'Powder for injection', array['50 mg (liposomal complex) in vial', '50 mg (as sodium deoxycholate) in vial'], 'Antifungal medicines'),
  ('Ampicillin', 'Powder for injection', array['500 mg', '1 g (as sodium) in vial'], 'Medicines for central nervous system infections'),
  ('Anidulafungin', null, '{}', 'Antifungal medicines'),
  ('Ansuvimab', 'Powder for injection', array['400 mg'], 'Medicines for Ebola virus disease'),
  ('Anti-D immunoglobulin', 'Injection', array['250 micrograms in single-dose vial'], 'Human immunoglobulins'),
  ('Anti-rabies immunoglobulin', 'Injection', array['150 IU/mL in vial'], 'Human immunoglobulins'),
  ('Anti-tetanus immunoglobulin', 'Injection', array['500 IU in vial'], 'Human immunoglobulins'),
  ('Apixaban', null, '{}', 'Medicines affecting coagulation'),
  ('Aprepitant', 'Capsule', array['80 mg', '125 mg', '165 mg Powder for oral suspension: 125 mg in sachet'], 'Antiemetic medicines'),
  ('Aripiprazole', null, '{}', 'Medicines for psychotic disorders'),
  ('Arpraziquantel', null, '{}', 'Antischistosomals and other antitrematode medicines'),
  ('Arsenic trioxide', 'Concentrate for solution for infusion', array['1 mg/mL', '2 mg/mL'], 'Cytotoxic medicines'),
  ('Artemether', 'Oily injection', array['20 mg/mL', '40 mg/mL in 1 mL ampoule'], 'Antimalarial medicines'),
  ('Artemether + lumefantrine', 'Tablet', array['20 mg + 120 mg'], 'Antimalarial medicines'),
  ('Artemether + lumefantrine', 'Tablet (dispersible)', array['20 mg + 120 mg'], 'Antimalarial medicines'),
  ('Artesunate', 'Powder for injection', array['30 mg', '60 mg', '120 mg in vial'], 'Antimalarial medicines'),
  ('Artesunate â€“ sulfadoxine + pyrimethamine', 'Co-packaged scored tablets', array['artesunate 50 mg and sulfadoxine + pyrimethamine 500 mg + 25 mg chloroquine Oral liquid: 50 mg/5 mL (base)'], 'Antimalarial medicines'),
  ('Artesunate â€“ sulfadoxine + pyrimethamine', 'Tablet', array['150 mg (base)'], 'Antimalarial medicines'),
  ('Artesunate + amodiaquine', 'Tablet', array['25 mg + 67.5 mg', '50 mg + 135 mg', '100 mg + 270 mg'], 'Antimalarial medicines'),
  ('Artesunate + mefloquine', 'Tablet', array['25 mg + 50 mg (as hydrochloride)', '100 mg + 200 mg (as hydrochloride)'], 'Antimalarial medicines'),
  ('Artesunate + pyronaridine', 'Granules', array['20 mg + 60 mg (tetraphosphate)'], 'Antimalarial medicines'),
  ('Artesunate + pyronaridine', 'Tablet', array['60 mg + 180 mg (tetraphosphate)'], 'Antimalarial medicines'),
  ('Ascorbic acid', 'Tablet', array['50 mg'], 'Vitamins and minerals'),
  ('Atazanavir + ritonavir', 'Tablet (heat stable)', array['300 mg (as sulfate) + 100 mg'], 'Antiretrovirals'),
  ('Atenolol', null, '{}', 'Antihypertensive medicines'),
  ('Atezolizumab', null, '{}', 'Immunomodulators'),
  ('Atoltivimab + maftivimab + odesivimab', 'Injection', array['241.7 mg + 241.7 mg + 241.7 mg in 14.5 mL vial'], 'Medicines for Ebola virus disease'),
  ('Atorvastatin', null, '{}', 'Lipid-lowering agents'),
  ('Atracurium', 'Injection', array['10 mg/mL (besylate)'], 'Muscle relaxants (peripherally-acting) and cholinesterase inhibitors'),
  ('Atropine', 'Injection', array['400 micrograms/mL', '1 mg/mL (sulfate) in 1 mL ampoule or vial'], 'Preoperative medication and sedation for short-term procedures'),
  ('Azathioprine', 'Oral liquid', array['10 mg/mL'], 'Immunomodulators for non-malignant disease'),
  ('Azathioprine', 'Powder for injection', array['50 mg', '100 mg (as sodium salt) in vial'], 'Immunomodulators for non-malignant disease'),
  ('Azathioprine', 'Tablet', array['25 mg', '50 mg'], 'Immunomodulators for non-malignant disease'),
  ('Azathioprine', 'Tablet (scored)', array['50 mg'], 'Immunomodulators for non-malignant disease'),
  ('Azithromycin', 'Powder for oral liquid', array['200 mg/5 mL (anhydrous)'], 'Watch group antibiotics'),
  ('Azithromycin', 'Solid oral dosage form', array['250 mg', '500 mg (anhydrous)'], 'Watch group antibiotics'),
  ('Azithromycin', 'Solution (eye drops)', array['1.5%'], 'Watch group antibiotics'),
  ('Baclofen', 'Intrathecal injection', array['500 micrograms/mL in ampoule'], 'Medicines for cerebral palsy'),
  ('Baclofen', 'Oral liquid', array['10 mg/5 mL'], 'Medicines for cerebral palsy'),
  ('Baclofen', 'Tablet', array['10 mg'], 'Medicines for cerebral palsy'),
  ('Beclometasone', null, '{}', 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Beclometasone + formoterol', null, '{}', 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Bedaquiline', 'Tablet', array['20 mg', '100 mg'], 'Antituberculosis medicines'),
  ('Bendamustine', 'Injection', array['45 mg/0.5 mL', '180 mg/2 mL'], 'Cytotoxic medicines'),
  ('Benzathine benzylpenicillin', 'Powder for injection', array['1.2 million IU (â‰ˆ 900 mg) in vial', '2.4 million IU (â‰ˆ 1.8 g) in vial'], 'Access group antibiotics'),
  ('Benznidazole', 'Tablet', array['12.5 mg Tablet (scored): 50 mg', '100 mg'], 'Antitrypanosomal medicines'),
  ('Benzoyl peroxide', 'Cream or lotion', array['5%'], 'Medicines affecting skin differentiation and proliferation'),
  ('Benzyl benzoate', 'Lotion', array['25%'], 'Scabicides and pediculicides'),
  ('Benzylpenicillin', 'Powder for injection', array['600 mg (= 1 million IU)', '3 g (= 5 million IU) (sodium or potassium salt) in vial'], 'Medicines for central nervous system infections'),
  ('Beractant', 'Suspension for intratracheal instillation', array['25 mg/mL'], 'Medicines administered to the neonate [c]'),
  ('Bicalutamide', 'Tablet', array['50 mg'], 'Hormones and antihormones'),
  ('Bisacodyl', null, '{}', 'Laxatives'),
  ('Bisoprolol', 'Tablet', array['1.25 mg', '5 mg'], 'Antianginal medicines'),
  ('Bleomycin', 'Powder for injection', array['15 000 IU (as sulfate) in vial'], 'Cytotoxic medicines'),
  ('Bortezomib', 'Powder for injection', array['3.5 mg in vial'], 'Targeted therapies'),
  ('Bromocriptine', null, '{}', 'Medicines for disorders of the pituitary hormone system'),
  ('Budesonide', 'Nasal spray', array['32 micrograms', '64 micrograms per actuation'], 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Budesonide', 'Powder for inhalation', array['100 micrograms per actuation', '200 micrograms per actuation in dry powder inhaler'], 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Budesonide', 'Suspension for inhalation', array['100 micrograms per actuation', '200 micrograms per actuation in pressurized metered-dose inhaler'], 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Budesonide + formoterol', 'Powder for inhalation', array['100 micrograms + 6 micrograms per actuation', '200 micrograms + 6 micrograms per actuation in dry powder inhaler'], 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Budesonide + salmeterol', null, '{}', 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Bumetanide', null, '{}', 'Medicines used in heart failure'),
  ('Bupivacaine', 'Injection', array['0.25%', '0.5% (hydrochloride)'], 'Local anaesthetics'),
  ('Bupivacaine', 'Injection for spinal anaesthesia', array['0.5% (hydrochloride) in 4 mL ampoule in 8% glucose solution'], 'Local anaesthetics'),
  ('Buprenorphine', null, '{}', 'Medicines for opioid use disorders'),
  ('Bupropion', 'Tablet (sustained-release)', array['150 mg (hydrochloride)'], 'Medicines for nicotine use disorders'),
  ('Cabergoline', 'Tablet', array['0.5 mg', '1 mg'], 'Medicines for disorders of the pituitary hormone system'),
  ('Caffeine citrate', 'Injection', array['20 mg/mL (equivalent to 10 mg caffeine base/mL)'], 'Medicines administered to the neonate [c]'),
  ('Caffeine citrate', 'Oral liquid', array['20 mg/mL (equivalent to 10 mg caffeine base/mL)'], 'Medicines administered to the neonate [c]'),
  ('Calcipotriol', 'Cream or ointment', array['50 micrograms/mL (0.005%)'], 'Medicines affecting skin differentiation and proliferation'),
  ('Calcipotriol', 'Lotion', array['50 micrograms/mL (0.005%)'], 'Medicines affecting skin differentiation and proliferation'),
  ('Calcitriol', null, '{}', 'Medicines affecting skin differentiation and proliferation'),
  ('Calcium folinate (leucovorin calcium)', 'Injection', array['3 mg/mL in 10 mL ampoule', '7.5 mg/mL in 2 mL ampoule', '10 mg/mL in 5 mL ampoule'], 'Cytotoxic medicines'),
  ('Calcium folinate (leucovorin calcium)', 'Tablet', array['5 mg', '15 mg', '25 mg'], 'Cytotoxic medicines'),
  ('Calcium gluconate', 'Injection', array['100 mg/mL (10%) in 10 mL ampoule or vial', '100 mg/mL in 10 mL ampoule'], 'Specific'),
  ('Canagliflozin', null, '{}', 'Hypoglycaemic agents'),
  ('Capecitabine', 'Tablet', array['150 mg', '500 mg'], 'Cytotoxic medicines'),
  ('Carbachol', null, '{}', 'Miotics and antiglaucoma medicines'),
  ('Carbamazepine', 'Oral liquid', array['100 mg/5 mL'], 'Antiseizure medicines'),
  ('Carbamazepine', 'Tablet (chewable)', array['100 mg', '200 mg'], 'Antiseizure medicines'),
  ('Carbamazepine', 'Tablet (scored)', array['100 mg', '200 mg', '400 mg'], 'Antiseizure medicines'),
  ('Carbetocin', 'Injection (heat stable)', array['100 micrograms/mL'], 'Uterotonics'),
  ('Carbimazole', null, '{}', 'Thyroid hormones and antithyroid medicines'),
  ('Carboplatin', 'Injection', array['50 mg/5 mL', '150 mg/15 mL', '450 mg/45 mL', '600 mg/60 mL'], 'Cytotoxic medicines'),
  ('Carvedilol', null, '{}', 'Antianginal medicines'),
  ('Caspofungin', null, '{}', 'Antifungal medicines'),
  ('Cefalexin', 'Powder for oral liquid', array['125 mg/5 mL', '250 mg/5 mL (anhydrous)'], 'Access group antibiotics'),
  ('Cefalexin', 'Solid oral dosage form', array['250 mg', '500 mg (as monohydrate)'], 'Access group antibiotics'),
  ('Cefalexin', 'Tablet (dispersible)', array['125 mg', '250 mg'], 'Access group antibiotics'),
  ('Cefazolin', 'Powder for injection', array['1 g (as sodium salt) in vial'], 'Access group antibiotics'),
  ('Cefiderocol', 'Powder for injection', array['1 g (as sulfate toxylate) in vial'], 'Reserve group antibiotics'),
  ('Cefixime', 'Powder for oral liquid', array['100 mg/5 mL'], 'Watch group antibiotics'),
  ('Cefixime', 'Solid oral dosage form', array['200 mg', '400 mg (as trihydrate)'], 'Watch group antibiotics'),
  ('Cefotaxime', 'Powder for injection', array['250 mg', '500 mg', '1 g', '2 g (as sodium) in vial'], 'Medicines for central nervous system infections'),
  ('Ceftazidime', 'Powder for injection', array['250 mg', '1 g (as pentahydrate) in vial'], 'Watch group antibiotics'),
  ('Ceftazidime + avibactam', 'Powder for injection', array['2 g + 0.5 g in vial'], 'Reserve group antibiotics'),
  ('Ceftolozane + tazobactam', 'Powder for injection', array['1 g + 0.5 g in vial'], 'Reserve group antibiotics'),
  ('Ceftriaxone', 'Powder for injection', array['250 mg', '500 mg', '1 g', '2 g (as sodium) in vial', '1 g (as sodium) in vial'], 'Watch group antibiotics'),
  ('Cefuroxime', 'Powder for injection', array['250 mg', '750 mg', '1.5 g (as sodium) in vial'], 'Watch group antibiotics'),
  ('Cemiplimab', null, '{}', 'Immunomodulators'),
  ('Certolizumab pegol', null, '{}', 'Immunomodulators for non-malignant disease'),
  ('Cetirizine', null, '{}', 'Antiallergics and medicines used in anaphylaxis'),
  ('Chlorambucil', 'Tablet', array['2 mg'], 'Cytotoxic medicines'),
  ('Chlorhexidine', 'Solution', array['5% (digluconate)'], 'Antiseptics'),
  ('Chlorhexidine', 'Solution or gel', array['7.1% (digluconate) delivering 4% chlorhexidine (for umbilical cord care)'], 'Antiseptics'),
  ('Chlorine base compound', 'Liquid', array['(0.1% available chlorine) for solution'], 'Disinfectants'),
  ('Chlorine base compound', 'Powder', array['(0.1% available chlorine) for solution'], 'Disinfectants'),
  ('Chlorine base compound', 'Solid', array['(0.1% available chlorine) for solution'], 'Disinfectants'),
  ('Chloroquine', 'Oral liquid', array['50 mg/5 mL (base)'], 'Antimalarial medicines'),
  ('Chloroquine', 'Tablet', array['150 mg (base)', '100 mg', '150 mg (as phosphate or sulfate)'], 'Antimalarial medicines'),
  ('Chlorothiazide', null, '{}', 'Antihypertensive medicines'),
  ('Chlorpromazine', null, '{}', 'Medicines for psychotic disorders'),
  ('Chlortalidone', null, '{}', 'Diuretics'),
  ('Chlortetracycline', null, '{}', 'Anti-infective agents'),
  ('Chlorthalidone', null, '{}', 'Antihypertensive medicines'),
  ('Ciclesonide', null, '{}', 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Ciclosporin', 'Capsule', array['25 mg'], 'Immunomodulators for non-malignant disease'),
  ('Ciclosporin', 'Concentrate for injection', array['50 mg/mL in 1 mL ampoule'], 'Immunomodulators for non-malignant disease'),
  ('Ciclosporin', 'Oral liquid', array['100 mg/mL'], 'Immunomodulators for non-malignant disease'),
  ('Ciprofloxacin', 'Oral liquid', array['250 mg/5 mL (anhydrous)'], 'Watch group antibiotics'),
  ('Ciprofloxacin', 'Solid oral dosage form', array['100 mg', '250 mg', '500 mg (as hydrochloride)'], 'Watch group antibiotics'),
  ('Ciprofloxacin', 'Solution (ear drops)', array['0.3% (as hydrochloride)'], 'Watch group antibiotics'),
  ('Ciprofloxacin', 'Solution for IV infusion', array['2 mg/mL (as hyclate)'], 'Watch group antibiotics'),
  ('Cisplatin', 'Injection', array['10 mg/10 mL', '20 mg/20 mL', '50 mg/50 mL', '100 mg/100 mL'], 'Cytotoxic medicines'),
  ('Citalopram', null, '{}', 'Medicines for depressive disorders'),
  ('Cladribine', 'Tablet', array['10 mg'], 'Medicines for multiple sclerosis'),
  ('Clindamycin', 'Capsule', array['150 mg (as hydrochloride)'], 'Access group antibiotics'),
  ('Clindamycin', 'Injection', array['150 mg/mL (as phosphate)', '600 mg/4 mL (as phosphate)', '900 mg/6 mL (as phosphate)'], 'Access group antibiotics'),
  ('Clindamycin', 'Powder for oral liquid', array['75 mg/5 mL (as palmitate hydrochloride)'], 'Access group antibiotics'),
  ('Clofazimine', 'Solid oral dosage form', array['50 mg', '100 mg'], 'Antileprosy medicines'),
  ('Clomifene', 'Tablet', array['50 mg (citrate)'], 'Ovulation inducers'),
  ('Clomipramine', 'Capsule', array['10 mg', '25 mg (hydrochloride)'], 'Medicines for obsessive compulsive disorders'),
  ('Clopidogrel', 'Tablet', array['75 mg', '300 mg'], 'Anti-platelet medicines'),
  ('Clotrimazole', 'Vaginal cream', array['1%', '10%'], 'Antifungal medicines'),
  ('Clotrimazole', 'Vaginal tablet', array['100 mg', '500 mg'], 'Antifungal medicines'),
  ('Clozapine', 'Solid oral dosage form', array['25 mg to 200 mg'], 'Medicines for psychotic disorders'),
  ('Coagulation factor IX, recombinant', 'Lyophilized powder for solution for injection', array['250 IU, 500 IU, 1000 IU, 1500 IU, 2000 IU, 3000 IU, 4000 IU in vial'], 'Coagulation factors'),
  ('Coagulation factor VIII, recombinant', 'Lyophilized powder for solution for injection', array['250 IU, 500 IU, 1000 IU, 1500 IU, 2000 IU, 3000 IU, 4000 IU in vial'], 'Coagulation factors'),
  ('Coal tar', 'Solution', array['5%'], 'Medicines affecting skin differentiation and proliferation'),
  ('Codeine', 'Tablet', array['30 mg (phosphate)'], 'Opioid analgesics'),
  ('Colecalciferol', 'Oral liquid', array['400 IU/mL'], 'Vitamins and minerals'),
  ('Colecalciferol', 'Solid oral dosage form', array['400 IU', '1000 IU'], 'Vitamins and minerals'),
  ('Colistin', 'Powder for injection', array['1 million IU (as colistemethate sodium) (equivalent to 34 mg colistin base activity) in vial'], 'Reserve group antibiotics'),
  ('Cryoprecipitate, native', null, '{}', 'Blood and blood components'),
  ('Cyclizine', 'Injection', array['50 mg/mL (lactate)'], 'Medicines for other common symptoms in palliative care'),
  ('Cyclizine', 'Tablet', array['50 mg (hydrochloride)'], 'Medicines for other common symptoms in palliative care'),
  ('Cyclopentolate', null, '{}', 'Ophthalmic medicines'),
  ('Cyclopentolate hydrochloride', null, '{}', 'Mydriatics'),
  ('Cyclophosphamide', 'Powder for injection', array['500 mg', '1 g', '2 g in vial'], 'Cytotoxic medicines'),
  ('Cyclophosphamide', 'Solid oral dosage form', array['25 mg', '50 mg'], 'Cytotoxic medicines'),
  ('Cycloserine', 'Solid oral dosage form', array['125 mg', '250 mg'], 'Antituberculosis medicines'),
  ('Cytarabine', 'Injection', array['100 mg/mL in vial'], 'Cytotoxic medicines'),
  ('Cytarabine', 'Powder for injection', array['100 mg in vial'], 'Cytotoxic medicines'),
  ('Cytisine (cytisinicline)', 'Tablet', array['1.5 mg'], 'Medicines for nicotine use disorders'),
  ('Dabigatran', 'Capsule', array['110 mg', '150 mg'], 'Medicines affecting coagulation'),
  ('Dacarbazine', 'Powder for injection', array['100 mg', '200 mg in vial'], 'Cytotoxic medicines'),
  ('Daclatasvir', 'Tablet', array['30 mg', '60 mg (as dihydrochloride)'], 'Antihepatitis medicines'),
  ('Daclatasvir + sofosbuvir', 'Tablet', array['60 mg (as dihydrochloride) + 400 mg'], 'Antihepatitis medicines'),
  ('Dactinomycin', 'Powder for injection', array['500 micrograms in vial'], 'Cytotoxic medicines'),
  ('Dalteparin', null, '{}', 'Medicines affecting coagulation'),
  ('Dapagliflozin', null, '{}', 'Hypoglycaemic agents'),
  ('Dapsone', 'Tablet', array['25 mg', '50 mg', '100 mg'], 'Antileprosy medicines'),
  ('Darbepoetin alfa', null, '{}', 'Antianaemia medicines'),
  ('Darunavir', 'Tablet', array['75 mg', '400 mg', '600 mg', '800 mg'], 'Antiretrovirals'),
  ('Dasatinib', 'Tablet', array['20 mg', '50 mg', '70 mg', '80 mg', '100 mg', '140 mg'], 'Targeted therapies'),
  ('Daunorubicin', 'Injection', array['2 mg/mL', '5 mg/mL (as hydrochloride) in vial'], 'Cytotoxic medicines'),
  ('Daunorubicin', 'Powder for injection', array['20 mg', '50 mg (as hydrochloride) in vial'], 'Cytotoxic medicines'),
  ('Deferasirox', 'Tablet (dispersible)', array['100 mg', '125 mg', '250 mg', '400 mg', '500 mg'], 'Medicines for sickle-cell disease'),
  ('Deferasirox', 'Tablet (film-coated)', array['90 mg', '180 mg', '360 mg'], 'Medicines for sickle-cell disease'),
  ('Deferiprone', null, '{}', 'Medicines for sickle-cell disease'),
  ('Deferoxamine', 'Powder for injection', array['500 mg (mesilate) in vial'], 'Specific'),
  ('Delamanid', 'Tablet', array['50 mg'], 'Antituberculosis medicines'),
  ('Delamanid', 'Tablet (dispersible)', array['25 mg'], 'Antituberculosis medicines'),
  ('Desmopressin', 'Injection', array['4 micrograms/mL (acetate) in 1 mL ampoule'], 'Medicines affecting coagulation'),
  ('Desmopressin', 'Nasal spray', array['150 micrograms (acetate) per actuation'], 'Medicines affecting coagulation'),
  ('Dexamethasone', 'Injection', array['4 mg/mL dexamethasone phosphate (as sodium phosphate) (equivalent to 3.3 mg/mL dexamethasone base) in 1 mL ampoule'], 'Medicines for other common symptoms in palliative care'),
  ('Dexamethasone', 'Oral liquid', array['0.5 mg/5 mL', '2 mg/5 mL (as sodium phosphate)'], 'Medicines for other common symptoms in palliative care'),
  ('Dexamethasone', 'Tablet', array['0.5 mg', '0.75 mg', '1.5 mg', '2 mg', '4 mg (as dexamethasone base)'], 'Medicines for other common symptoms in palliative care'),
  ('Dextran 70', 'Injectable solution', array['6%'], 'Plasma substitutes'),
  ('Diazepam', 'Injection', array['5 mg/mL'], 'Medicines for other common symptoms in palliative care'),
  ('Diazepam', 'Oral liquid', array['2 mg/5 mL'], 'Medicines for other common symptoms in palliative care'),
  ('Diazepam', 'Rectal gel', array['5 mg/mL in 0.5 mL, 2 mL, 4 mL rectal delivery system'], 'Medicines for other common symptoms in palliative care'),
  ('Diazepam', 'Rectal solution', array['2 mg/mL in 1.25 mL, 2.5 mL rectal tube', '4 mg/mL in 2.5 mL rectal tube'], 'Medicines for other common symptoms in palliative care'),
  ('Diazepam', 'Tablet (scored)', array['2 mg', '5 mg', '10 mg'], 'Medicines for other common symptoms in palliative care'),
  ('Diazoxide', 'Oral liquid', array['50 mg/mL'], 'Medicines for hypoglycaemia'),
  ('Diazoxide', 'Tablet', array['50 mg'], 'Medicines for hypoglycaemia'),
  ('Diethylcarbamazine', 'Tablet', array['50 mg', '100 mg (dihydrogen citrate)'], 'Antifilarials'),
  ('Digoxin', 'Injection', array['250 micrograms/mL in 2 mL ampoule', '100 micrograms/mL in 1 mL ampoule'], 'Antiarrhythmic medicines'),
  ('Digoxin', 'Oral liquid', array['50 micrograms/mL'], 'Antiarrhythmic medicines'),
  ('Digoxin', 'Tablet', array['62.5 micrograms', '250 micrograms', '125 micrograms'], 'Antiarrhythmic medicines'),
  ('Dihydroartemisinin + piperaquine', 'Tablet', array['20 mg + 160 mg (phosphate)', '40 mg + 320 mg (phosphate)', '60 mg + 480 mg (phosphate)', '80 mg + 640 mg (phosphate)'], 'Antimalarial medicines'),
  ('Dihydroartemisinin + piperaquine', 'Tablet (dispersible)', array['20 mg + 160 mg (phosphate)', '40 mg + 320 mg (phosphate)'], 'Antimalarial medicines'),
  ('Dimercaprol', 'Injection in oil', array['50 mg/mL in 2 mL ampoule', '100 mg/mL in 3 mL ampoule'], 'Specific'),
  ('Dinoprostone (prostaglandin E2)', null, '{}', 'Medicines administered to the neonate [c]'),
  ('Diphtheria antitoxin', 'Injection', array['10 000 IU', '20 000 IU in vial'], 'Sera, immunoglobulins and monoclonal antibodies'),
  ('Docetaxel', 'Injection', array['20 mg/mL', '40 mg/mL'], 'Cytotoxic medicines'),
  ('Docusate sodium', 'Capsule', array['100 mg'], 'Medicines for other common symptoms in palliative care'),
  ('Docusate sodium', 'Oral liquid', array['12.5 mg/5 mL', '50 mg/5 mL'], 'Medicines for other common symptoms in palliative care'),
  ('Dolasetron', null, '{}', 'Medicines for other common symptoms in palliative care'),
  ('Dolutegravir', 'Tablet (dispersible, scored)', array['10 mg'], 'Antiretrovirals'),
  ('Dolutegravir + lamivudine + tenofovir', 'Tablet', array['50 mg + 300 mg + 300 mg (tenofovir disoproxil fumarate â€“ equivalent to 245 mg tenofovir disoproxil) efavirenz + emtricitabine + tenofovir', '600 mg + 200 mg + 300 mg (tenofovir disoproxil fumarate â€“ equivalent to 245 mg tenofovir disoproxil)'], 'Antiretrovirals'),
  ('Dopamine', 'Injection', array['40 mg/mL (hydrochloride) in 5 mL vial'], 'Medicines used in heart failure'),
  ('Doxorubicin', 'Injection', array['2 mg/mL (hydrochloride) in vial'], 'Cytotoxic medicines'),
  ('Doxorubicin', 'Powder for injection', array['10 mg', '50 mg (hydrochloride) in vial'], 'Cytotoxic medicines'),
  ('Doxorubicin (as pegylated liposomal)', 'Injection', array['2 mg/mL (hydrochloride) in 10 mL, 25 mL vial âˆ’ Kaposi sarcoma etoposide Capsule: 50 mg, 100 mg', '20 mg/mL in 5 mL ampoule'], 'Cytotoxic medicines'),
  ('Doxorubicin (as pegylated liposomal)', 'Powder for injection', array['100 mg (as phosphate) in vial'], 'Cytotoxic medicines'),
  ('Doxycycline', 'Oral liquid', array['50 mg/5 mL (calcium)'], 'Access group antibiotics'),
  ('Doxycycline', 'Powder for injection', array['100 mg in vial'], 'Access group antibiotics'),
  ('Doxycycline', 'Powder for oral liquid', array['25 mg/5 mL (monohydrate)'], 'Access group antibiotics'),
  ('Doxycycline', 'Solid oral dosage form', array['50 mg', '100 mg (as hyclate)'], 'Access group antibiotics'),
  ('Doxycycline', 'Tablet (dispersible)', array['100 mg (as monohydrate)'], 'Access group antibiotics'),
  ('Dulaglutide', null, '{}', 'Hypoglycaemic agents'),
  ('Edoxaban', null, '{}', 'Medicines affecting coagulation'),
  ('Efavirenz', 'Tablet', array['600 mg'], 'Antiretrovirals'),
  ('Efavirenz + lamivudine + tenofovir', 'Tablet', array['400 mg + 300 mg + 300 mg (tenofovir disoproxil fumarate â€“ equivalent to 245 mg tenofovir disoproxil) emtricitabine + tenofovir', '200 mg + 300 mg (tenofovir disoproxil fumarate â€“ equivalent to 245 mg tenofovir disoproxil)'], 'Antiretrovirals'),
  ('Eflornithine', 'Injection', array['200 mg/mL (hydrochloride) in 50 mL bottle'], 'Antitrypanosomal medicines'),
  ('Eletriptan', null, '{}', 'Medicines for headache disorders'),
  ('Elexacaftor + tezacaftor + ivacaftor', 'Granules', array['80 mg + 40 mg + 60 mg', '100 mg + 50 mg + 75 mg in sachet'], 'Medicines for cystic fibrosis'),
  ('Elexacaftor + tezacaftor + ivacaftor', 'Tablet', array['50 mg + 25 mg + 37.5 mg', '100 mg + 50 mg + 75 mg'], 'Medicines for cystic fibrosis'),
  ('Emicizumab', 'Injection', array['12 mg/0.4 mL', '30 mg/mL', '60 mg/0.4 mL', '105 mg/0.7 mL', '150 mg/mL', '300 mg/2 mL in vial'], 'Medicines affecting coagulation'),
  ('Empagliflozin', 'Tablet', array['10 mg', '25 mg'], 'Hypoglycaemic agents'),
  ('Entecavir', 'Oral liquid', array['0.05 mg/mL Tablet: 0.5 mg', '1 mg tenofovir disoproxil fumarate Tablet: 300 mg (tenofovir disoproxil fumarate â€“ equivalent to 245 mg tenofovir disoproxil)'], 'Antihepatitis medicines'),
  ('Enzalutamide', null, '{}', 'Hormones and antihormones'),
  ('Ephedrine', 'Injection', array['30 mg/mL (hydrochloride) in 1 mL ampoule'], 'Local anaesthetics'),
  ('Epinephrine (adrenaline)', 'Injection', array['1 mg/mL (as hydrochloride or hydrogen tartrate) in 1 mL ampoule', '100 micrograms/mL (as acid tartrate or hydrochloride) in 10 mL ampoule'], 'Antiallergics and medicines used in anaphylaxis'),
  ('Epinephrine (adrenaline)', 'Solution (eye drops)', array['2% (as hydrochloride)'], 'Antiallergics and medicines used in anaphylaxis'),
  ('Epoetin alfa, beta and theta', null, '{}', 'Antianaemia medicines'),
  ('Equine rabies immunoglobulin', 'Injection', array['150 IU/mL', '200 IU/mL', '300 IU/mL', '400 IU/mL in vial'], 'Sera, immunoglobulins and monoclonal antibodies'),
  ('Ergocalciferol', 'Oral liquid', array['250 micrograms/mL (10 000 IU/mL)'], 'Vitamins and minerals'),
  ('Ergocalciferol', 'Solid oral dosage form', array['1.25 mg (50 000 IU)'], 'Vitamins and minerals'),
  ('Ergometrine', 'Injection', array['200 micrograms (hydrogen maleate) in 1 mL ampoule'], 'Uterotonics'),
  ('Erlotinib', 'Tablet', array['100 mg, 150 mg'], 'Targeted therapies'),
  ('Erythromycin', 'Ointment', array['0.5% âˆ’ Infections due to Chlamydia trachomatis or Neisseria gonorrhoea'], 'Anti-infective agents'),
  ('Escitalopram', null, '{}', 'Medicines for depressive disorders'),
  ('Etanercept', null, '{}', 'Immunomodulators for non-malignant disease'),
  ('Ethambutol', 'Tablet', array['100 mg', '400 mg (hydrochloride)'], 'Antituberculosis medicines'),
  ('Ethambutol', 'Tablet (dispersible)', array['100 mg ethambutol + isoniazid + pyrazinamide + rifampicin Tablet: 275 mg + 75 mg + 400 mg + 150 mg'], 'Antituberculosis medicines'),
  ('Ethambutol + isoniazid + rifampicin', 'Tablet', array['275 mg + 75 mg + 150 mg'], 'Antituberculosis medicines'),
  ('Ethanol', 'Solution', array['70% (denatured)'], 'Antiseptics'),
  ('Ethinylestradiol + etonogestrel', 'Vaginal ring', array['containing 2.7 mg + 11.7 mg'], 'Intravaginal contraceptives'),
  ('Ethinylestradiol + levonorgestrel', 'Tablet', array['30 micrograms + 150 micrograms'], 'Oral hormonal contraceptives'),
  ('Ethinylestradiol + norethisterone', 'Tablet', array['35 micrograms + 1 mg'], 'Oral hormonal contraceptives'),
  ('Ethosuximide', 'Capsule', array['250 mg'], 'Antiseizure medicines'),
  ('Ethosuximide', 'Oral liquid', array['250 mg/5 mL'], 'Antiseizure medicines'),
  ('Etonogestrel-releasing implant', 'Single-rod etonogestrel-releasing implant', array['containing 68 mg of etonogestrel'], 'Implantable contraceptives'),
  ('Everolimus', 'Tablet', array['2.5 mg', '5 mg', '7.5 mg', '10 mg'], 'Targeted therapies'),
  ('Everolimus', 'Tablet (dispersible)', array['2 mg', '3 mg', '5 mg'], 'Targeted therapies'),
  ('Fentanyl', 'Transdermal patch', array['12 micrograms/hr', '25 micrograms/hr', '50 micrograms/hr', '75 micrograms/hr', '100 micrograms/hr'], 'Opioid analgesics'),
  ('Ferrous salt', 'Oral liquid', array['equivalent to 9 mg/mL elemental iron', 'equivalent to 25 mg/mL elemental iron'], 'Antianaemia medicines'),
  ('Ferrous salt', 'Tablet', array['equivalent to 60 mg â€“ 65 mg elemental iron'], 'Antianaemia medicines'),
  ('Ferrous salt + folic acid', 'Tablet', array['equivalent to 60 mg elemental iron + 400 micrograms folic acid'], 'Antianaemia medicines'),
  ('Fexinidazole', 'Tablet', array['600 mg'], 'Antitrypanosomal medicines'),
  ('Fexofenadine', null, '{}', 'Antiallergics and medicines used in anaphylaxis'),
  ('Fluconazole', 'Capsule', array['50 mg'], 'Antifungal medicines'),
  ('Fluconazole', 'Injection', array['2 mg/mL in vial'], 'Antifungal medicines'),
  ('Fluconazole', 'Oral liquid', array['50 mg/5 mL'], 'Antifungal medicines'),
  ('Fluconazole', 'Powder for oral liquid', array['50 mg/5 mL'], 'Antifungal medicines'),
  ('Flucytosine', 'Capsule', array['250 mg'], 'Antifungal medicines'),
  ('Flucytosine', 'Infusion', array['2.5 g in 250 mL'], 'Antifungal medicines'),
  ('Fludarabine', 'Powder for injection', array['50 mg (phosphate) in vial'], 'Cytotoxic medicines'),
  ('Fludarabine', 'Tablet', array['10 mg âˆ’ Chronic lymphocytic leukaemia'], 'Cytotoxic medicines'),
  ('Fludrocortisone', 'Oral liquid', array['100 micrograms/mL (acetate)'], 'Adrenal hormones and synthetic substitutes'),
  ('Fludrocortisone', 'Tablet', array['100 micrograms (acetate)'], 'Adrenal hormones and synthetic substitutes'),
  ('Fluorescein', 'Eye drops', array['1% (sodium salt)'], 'Ophthalmic medicines'),
  ('Fluoride', 'Gel', array['containing 2500 to 12 500 ppm fluoride (any type)'], 'Dental medicines and preparations'),
  ('Fluoride', 'Mouthrinse', array['containing 230 to 900 ppm fluoride (any type)'], 'Dental medicines and preparations'),
  ('Fluoride', 'Toothpaste, cream or gel', array['containing 1000 to 1500 ppm fluoride (any type)'], 'Dental medicines and preparations'),
  ('Fluoride', 'Varnish', array['containing 22 500 ppm fluoride (any type)'], 'Dental medicines and preparations'),
  ('Fluorouracil', 'Injection', array['50 mg/mL in vial'], 'Cytotoxic medicines'),
  ('Fluorouracil', 'Ointment', array['5%'], 'Cytotoxic medicines'),
  ('Fluoxetine', 'Solid oral dosage form', array['20 mg (as hydrochloride)'], 'Medicines for other common symptoms in palliative care'),
  ('Fluphenazine', 'Injection', array['25 mg (decanoate or enantate) in 1 mL ampoule'], 'Medicines for psychotic disorders'),
  ('Flutamide', null, '{}', 'Hormones and antihormones'),
  ('Fluticasone', null, '{}', 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Fluticasone + formoterol', null, '{}', 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Fluticasone furoate + vilanterol', null, '{}', 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Fluvastatin', null, '{}', 'Lipid-lowering agents'),
  ('Fluvoxamine', null, '{}', 'Medicines for depressive disorders'),
  ('Folic acid', 'Oral liquid', array['1 mg/mL'], 'Antianaemia medicines'),
  ('Folic acid', 'Tablet', array['400 micrograms', '1 mg', '5 mg'], 'Antianaemia medicines'),
  ('Fomepizole', 'Injection', array['5 mg/mL (sulfate) in 20 mL ampoule or 1 g/mL (base) in 1.5 mL ampoule or vial'], 'Specific'),
  ('Fosfomycin', 'Powder for injection', array['2 g', '4 g (as sodium) in vial'], 'Reserve group antibiotics'),
  ('Furosemide', 'Injection', array['10 mg/mL in 2 mL, 5 mL ampoule'], 'Medicines used in heart failure'),
  ('Furosemide', 'Oral liquid', array['20 mg/5 mL', '50 mg/5 mL'], 'Medicines used in heart failure'),
  ('Furosemide', 'Tablet', array['20 mg', '40 mg'], 'Medicines used in heart failure'),
  ('Gefitinib', null, '{}', 'Targeted therapies'),
  ('Gemcitabine', 'Powder for injection', array['200 mg', '1 g in vial'], 'Cytotoxic medicines'),
  ('Gentamicin', 'Injection', array['10 mg/mL (as sulfate)', '40 mg/mL (as sulfate) in 2 mL vial'], 'Medicines for central nervous system infections'),
  ('Gentamicin', 'Solution (eye drops)', array['0.3% (sulfate)'], 'Medicines for central nervous system infections'),
  ('Glass ionomer cement', 'Multi-use bottle', array['powder + liquid'], 'Dental medicines and preparations'),
  ('Glass ionomer cement', 'Powder (fluoro-alumino-silicate glass) contains', '{}', 'Dental medicines and preparations'),
  ('Glass ionomer cement', 'Single-use capsules', array['0.4 g powder + 0.09 mL liquid'], 'Dental medicines and preparations'),
  ('Glatiramer acetate', 'Injection (subcutaneous)', array['20 mg/mL', '40 mg/mL in pre-filled syringe'], 'Medicines for multiple sclerosis'),
  ('Glecaprevir + pibrentasvir', 'Granules', array['50 mg + 20 mg in sachet'], 'Antihepatitis medicines'),
  ('Glecaprevir + pibrentasvir', 'Tablet', array['100 mg + 40 mg'], 'Antihepatitis medicines'),
  ('Glucagon', 'Injection', array['1 mg/mL as powder and diluent'], 'Medicines for hypoglycaemia'),
  ('Glucose', 'Injectable solution', array['5% (isotonic)', '10% (hypertonic)', '50% (hypertonic)'], 'Parenteral'),
  ('Glucose with sodium chloride', 'Injectable solution', array['4% glucose, 0.18% sodium chloride (equivalent to Na + 30 mmol/L, Cl â€“ 30 mmol/L)', '5% glucose, 0.9% sodium chloride (equivalent to Na + 150 mmol/L and Cl â€“ 150 mmol/L)', '5% glucose, 0.45% sodium chloride (equivalent to Na + 75 mmol/L and Cl â€“ 75 mmol/L)'], 'Parenteral'),
  ('Glutaral', 'Solution', array['2%'], 'Disinfectants'),
  ('Glycerol', 'Cream', array['15% to 20%'], 'Moisturizers'),
  ('Glyceryl trinitrate', 'Tablet (sublingual)', array['500 micrograms'], 'Antianginal medicines'),
  ('Glycopyrronium', null, '{}', 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Golimumab', null, '{}', 'Immunomodulators for non-malignant disease'),
  ('Goserelin', null, '{}', 'Hormones and antihormones'),
  ('Granisetron', null, '{}', 'Medicines for other common symptoms in palliative care'),
  ('Griseofulvin', 'Oral liquid', array['125 mg/5 mL'], 'Antifungal medicines'),
  ('Griseofulvin', 'Solid oral dosage form', array['125 mg', '250 mg'], 'Antifungal medicines'),
  ('Haloperidol', 'Injection', array['5 mg in 1 mL ampoule', '5 mg/mL in 1 mL ampoule'], 'Medicines for other common symptoms in palliative care'),
  ('Haloperidol', 'Oral liquid', array['2 mg/mL'], 'Medicines for other common symptoms in palliative care'),
  ('Haloperidol', 'Solid oral dosage form', array['0.5 mg', '2 mg', '5 mg'], 'Medicines for other common symptoms in palliative care'),
  ('Haloperidol', 'Tablet', array['2 mg', '5 mg'], 'Medicines for other common symptoms in palliative care'),
  ('Haloperidol decanoate', null, '{}', 'Medicines for psychotic disorders'),
  ('Heparin sodium', 'Injection', array['1000 IU/mL', '5000 IU/mL', '20 000 IU/mL in 1 mL ampoule or vial', '5000 IU/mL in 1 mL ampoule or vial'], 'Medicines affecting coagulation'),
  ('Homatropine hydrobromide', null, '{}', 'Mydriatics'),
  ('Hydralazine', 'Powder for injection', array['20 mg (hydrochloride) in ampoule'], 'Antihypertensive medicines'),
  ('Hydralazine', 'Tablet', array['25 mg', '50 mg (hydrochloride)'], 'Antihypertensive medicines'),
  ('Hydrochlorothiazide', 'Oral liquid', array['50 mg/5 mL'], 'Antihypertensive medicines'),
  ('Hydrochlorothiazide', 'Solid oral dosage form', array['12.5 mg', '25 mg'], 'Antihypertensive medicines'),
  ('Hydrocortisone', 'Granules', array['0.5 mg', '1 mg', '2 mg', '5 mg in capsule'], 'Antiallergics and medicines used in anaphylaxis'),
  ('Hydrocortisone', 'Powder for injection', array['100 mg (as sodium succinate) in vial'], 'Antiallergics and medicines used in anaphylaxis'),
  ('Hydrocortisone', 'Retention enema', array['100 mg/60 mL'], 'Antiallergics and medicines used in anaphylaxis'),
  ('Hydrocortisone', 'Suppository', array['25 mg (acetate)'], 'Antiallergics and medicines used in anaphylaxis'),
  ('Hydrocortisone', 'Tablet', array['5 mg', '10 mg', '20 mg'], 'Antiallergics and medicines used in anaphylaxis'),
  ('Hydromorphone', null, '{}', 'Opioid analgesics'),
  ('Hydroxocobalamin', 'Injection', array['1 mg/mL (as acetate, as hydrochloride or as sulfate) in 1 mL ampoule'], 'Antianaemia medicines'),
  ('Hydroxychloroquine', 'Solid oral dosage form', array['200 mg (as sulfate)'], 'Disease-modifying anti-rheumatic drugs (DMARDs)'),
  ('Hydroxyurea (hydroxycarbamide)', 'Solid oral dosage form', array['100 mg', '200 mg', '300 mg', '400 mg', '500 mg', '1 g'], 'Cytotoxic medicines'),
  ('Hyoscine butylbromide', 'Injection', array['20 mg/mL'], 'Medicines for other common symptoms in palliative care'),
  ('Hyoscine hydrobromide', 'Injection', array['400 micrograms/mL', '600 micrograms/mL'], 'Medicines for other common symptoms in palliative care'),
  ('Hyoscine hydrobromide', 'Transdermal patches', array['1 mg/72 hours'], 'Medicines for other common symptoms in palliative care'),
  ('Hypochlorous acid', 'Solution (aqueous)', array['containing hypochlorous acid â‰¥ 150 parts per million'], 'Disinfectants'),
  ('Ibrutinib', 'Capsule', array['140 mg'], 'Targeted therapies'),
  ('Ibuprofen', 'Oral liquid', array['100 mg/5 mL', '100 mg/5 mL , 200 mg/5 mL'], 'Medicines for headache disorders'),
  ('Ibuprofen', 'Solution for injection', array['5 mg/mL'], 'Medicines for headache disorders'),
  ('Ibuprofen', 'Tablet', array['200 mg', '400 mg', '600 mg'], 'Medicines for headache disorders'),
  ('Ifosfamide', 'Powder for injection', array['500 mg', '1 g', '2 g in vial'], 'Cytotoxic medicines'),
  ('Imatinib', 'Solid oral dosage form', array['100 mg', '400 mg'], 'Targeted therapies'),
  ('Imipenem + cilastatin', null, '{}', 'Watch group antibiotics'),
  ('Indapamide', null, '{}', 'Antihypertensive medicines'),
  ('Indometacin', null, '{}', 'Medicines administered to the neonate [c]'),
  ('Infliximab', null, '{}', 'Immunomodulators for non-malignant disease'),
  ('Insulin aspart', null, '{}', 'Insulins'),
  ('Insulin degludec', null, '{}', 'Insulins'),
  ('Insulin detemir', null, '{}', 'Insulins'),
  ('Insulin glargine', null, '{}', 'Insulins'),
  ('Insulin glulisine', null, '{}', 'Insulins'),
  ('Insulin lispro', null, '{}', 'Insulins'),
  ('Intraperitoneal dialysis solution', 'Solution', array['of appropriate composition in accordance with local clinical guidelines'], 'Peritoneal dialysis solution'),
  ('Iodine', 'Iodized oil', array['480 mg iodine/mL in 10 mL ampoule or vial (oral or injectable)'], 'Antiseptics'),
  ('Iohexol', 'Injection', array['140 mg to 350 mg iodine/mL in 5 mL, 10 mL, 20 mL ampoule'], 'Radiocontrast media'),
  ('Ipratropium bromide', 'Solution for inhalation', array['20 micrograms per actuation in pressurized metered-dose inhaler'], 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Irinotecan', 'Injection', array['40 mg/2 mL in 2 mL vial', '100 mg/5 mL in 5 mL vial', '500 mg/25 mL in 25 mL vial'], 'Cytotoxic medicines'),
  ('Isoflurane', 'Inhalation', '{}', 'Inhalational medicines'),
  ('Isoniazid', 'Tablet', array['100 mg', '300 mg'], 'Antituberculosis medicines'),
  ('Isoniazid', 'Tablet (dispersible, scored)', array['100 mg'], 'Antituberculosis medicines'),
  ('Isoniazid + pyrazinamide + rifampicin', 'Tablet (dispersible)', array['50 mg + 150 mg + 75 mg'], 'Antituberculosis medicines'),
  ('Isoniazid + rifampicin', 'Tablet', array['75 mg + 150 mg', '150 mg + 300 mg'], 'Antituberculosis medicines'),
  ('Isoniazid + rifampicin', 'Tablet (dispersible)', array['50 mg + 75 mg'], 'Antituberculosis medicines'),
  ('Isoniazid + rifapentine', 'Tablet (scored)', array['300 mg + 300 mg'], 'Antituberculosis medicines'),
  ('Isosorbide dinitrate', 'Tablet (sublingual)', array['5 mg'], 'Antianginal medicines'),
  ('Itraconazole', 'Capsule', array['100 mg'], 'Antifungal medicines'),
  ('Itraconazole', 'Oral liquid', array['10 mg/mL'], 'Antifungal medicines'),
  ('Ivacaftor', 'Granules', array['59.5 mg', '75 mg in sachet'], 'Medicines for cystic fibrosis'),
  ('Ivacaftor', 'Tablet', array['75 mg', '150 mg'], 'Medicines for cystic fibrosis'),
  ('Ivermectin', 'Tablet', array['3 mg'], 'Intestinal anthelminthics'),
  ('Kanamycin', null, '{}', 'Anti-infective agents'),
  ('Ketamine', 'Injection', array['10 mg/mL', '50 mg/mL (as hydrochloride) in vial'], 'Injectable medicines'),
  ('Lactulose', 'Oral liquid', array['3.3 to 3.4 g/5 mL'], 'Medicines for other common symptoms in palliative care'),
  ('Lamivudine', 'Oral liquid', array['50 mg/5 mL'], 'Antiretrovirals'),
  ('Lamivudine', 'Tablet', array['150 mg'], 'Antiretrovirals'),
  ('Lamivudine + zidovudine', 'Tablet', array['30 mg + 60 mg', '150 mg + 300 mg'], 'Antiretrovirals'),
  ('Lamotrigine', 'Tablet', array['25 mg', '50 mg', '100 mg', '200 mg'], 'Antiseizure medicines'),
  ('Lamotrigine', 'Tablet (chewable, dispersible)', array['2 mg', '5 mg', '25 mg', '50 mg', '100 mg', '200 mg'], 'Antiseizure medicines'),
  ('Latanoprost', 'Solution (eye drops)', array['50 micrograms/mL'], 'Miotics and antiglaucoma medicines'),
  ('Ledipasvir + sofosbuvir', 'Tablet', array['90 mg + 400 mg'], 'Antihepatitis medicines'),
  ('Lenalidomide', 'Capsule', array['25 mg'], 'Immunomodulators'),
  ('Letrozole', 'Solid oral dosage form', array['2.5 mg'], 'Ovulation inducers'),
  ('Leuprorelin', 'Injection', array['7.5 mg', '22.5 mg in pre-filled syringe'], 'Hormones and antihormones'),
  ('Levamisole', 'Tablet', array['50 mg', '150 mg (as hydrochloride)'], 'Intestinal anthelminthics'),
  ('Levetiracetam', 'Concentrate solution for infusion', array['100 mg/mL in 5 mL ampoule or vial'], 'Antiseizure medicines'),
  ('Levetiracetam', 'Oral liquid', array['100 mg/mL Tablet: 250 mg', '500 mg', '750 mg', '1000 mg'], 'Antiseizure medicines'),
  ('Levetiracetam', 'Solution for infusion', array['5 mg/mL', '10 mg/mL', '15 mg/mL in 100 mL bag'], 'Antiseizure medicines'),
  ('Levofloxacin', 'Tablet', array['250 mg', '500 mg', '750 mg'], 'Antituberculosis medicines'),
  ('Levofloxacin', 'Tablet (dispersible)', array['100 mg'], 'Antituberculosis medicines'),
  ('Levonorgestrel', 'Tablet', array['30 micrograms', '750 micrograms (pack of two)', '1.5 mg'], 'Oral hormonal contraceptives'),
  ('Levonorgestrel-releasing implant', 'Two-rod levonorgestrel-releasing implant', array['each rod containing 75 mg of levonorgestrel (150 mg total)'], 'Implantable contraceptives'),
  ('Levonorgestrel-releasing intrauterine system', 'Intrauterine system', array['with reservoir containing 52 mg of levonorestrel'], 'Intrauterine devices'),
  ('Levothyroxine', 'Tablet', array['25 micrograms', '50 micrograms', '100 micrograms (sodium salt)'], 'Thyroid hormones and antithyroid medicines'),
  ('Lidocaine', 'Injection', array['0.5%', '1%', '2% (hydrochloride)', '20 mg/mL (hydrochloride) in 5 mL ampoule'], 'Local anaesthetics'),
  ('Lidocaine', 'Injection for spinal anaesthesia', array['5% (hydrochloride) in 2 mL ampoule in 7.5% glucose solution'], 'Local anaesthetics'),
  ('Lidocaine', 'Topical forms', array['2% to 4% (hydrochloride)'], 'Local anaesthetics'),
  ('Lidocaine + epinephrine (adrenaline)', 'Dental cartridge', array['2% (hydrochloride) + epinephrine 1:80 000'], 'Local anaesthetics'),
  ('Lidocaine + epinephrine (adrenaline)', 'Injection', array['1%', '2% (hydrochloride or sulfate) + epinephrine 1:200 000'], 'Local anaesthetics'),
  ('Linezolid', 'Injection for intravenous administration', array['2 mg/mL in 300 mL bag'], 'Reserve group antibiotics'),
  ('Linezolid', 'Powder for oral liquid', array['100 mg/5 mL'], 'Reserve group antibiotics'),
  ('Linezolid', 'Tablet', array['600 mg'], 'Reserve group antibiotics'),
  ('Linezolid', 'Tablet (dispersible, scored)', array['150 mg'], 'Reserve group antibiotics'),
  ('Linezolid', 'Tablet (dispersible)', array['150 mg'], 'Reserve group antibiotics'),
  ('Liraglutide', null, '{}', 'Hypoglycaemic agents'),
  ('Lithium carbonate', 'Solid oral dosage form', array['300 mg'], 'Medicines for bipolar disorders'),
  ('Loperamide', 'Solid oral dosage form', array['2 mg'], 'Medicines for other common symptoms in palliative care'),
  ('Lopinavir + ritonavir', 'Solid oral dosage form', array['40 mg + 10 mg'], 'Antiretrovirals'),
  ('Lopinavir + ritonavir', 'Tablet (heat stable)', array['100 mg + 25 mg', '200 mg + 50 mg'], 'Antiretrovirals'),
  ('Loratadine', 'Oral liquid', array['1 mg/mL'], 'Antiallergics and medicines used in anaphylaxis'),
  ('Loratadine', 'Tablet', array['10 mg'], 'Antiallergics and medicines used in anaphylaxis'),
  ('Loratadine', 'Tablet (chewable)', array['5 mg', '10 mg'], 'Antiallergics and medicines used in anaphylaxis'),
  ('Lorazepam', 'Injection', array['2 mg/mL in 1 mL ampoule', '4 mg/mL in 1 mL ampoule'], 'Antiseizure medicines'),
  ('Lovastatin', null, '{}', 'Lipid-lowering agents'),
  ('Magnesium sulfate', 'Injection', array['0.5 g/mL in 2 mL ampoule (equivalent to 1 g in 2 mL', '50% weight/volume)', '0.5 g/mL in 10 mL ampoule (equivalent to 5 g in 10 mL'], 'Antiseizure medicines'),
  ('Mannitol', 'Injectable solution', array['10%', '20%'], 'Diuretics'),
  ('Mannitol', 'Solution for infusion', array['10%', '20%'], 'Diuretics'),
  ('Mebendazole', 'Tablet (chewable)', array['100 mg', '500 mg', '100 mg , 500 mg'], 'Intestinal anthelminthics'),
  ('Medroxyprogesterone acetate', 'Injection (intramuscular)', array['150 mg/mL in 1 mL vial'], 'Progestogens'),
  ('Medroxyprogesterone acetate', 'Injection (subcutaneous)', array['104 mg/0.65 mL in pre-filled syringe or single-dose injection delivery system'], 'Progestogens'),
  ('Medroxyprogesterone acetate', 'Tablet', array['5 mg'], 'Progestogens'),
  ('Mefloquine', 'Tablet (scored)', array['250 mg (as hydrochloride)'], 'Antimalarial medicines'),
  ('Meglumine antimoniate', 'Injection', array['1.5 g/5 mL in 5 mL ampoule'], 'Antileishmaniasis medicines'),
  ('Meglumine iotroxate', 'Solution', array['5 g to 8 g iodine in 100 mL to 250 mL'], 'Radiocontrast media'),
  ('Melarsoprol', 'Injection', array['180 mg/5 mL in 5 mL ampoule (3.6% solution)'], 'Antitrypanosomal medicines'),
  ('Melphalan', 'Powder for injection', array['50 mg in vial'], 'Cytotoxic medicines'),
  ('Melphalan', 'Tablet', array['2 mg'], 'Cytotoxic medicines'),
  ('Mercaptopurine', 'Oral liquid', array['20 mg/mL'], 'Cytotoxic medicines'),
  ('Mercaptopurine', 'Tablet', array['50 mg'], 'Cytotoxic medicines'),
  ('Meropenem', 'Powder for injection', array['500 mg (as trihydrate)', '1 g (as trihydrate) in vial'], 'Antituberculosis medicines'),
  ('Meropenem + vaborbactam', 'Powder for injection', array['1 g (as trihydrate) + 1 g in vial'], 'Reserve group antibiotics'),
  ('Mesalazine', null, '{}', 'Anti-inflammatory medicines'),
  ('Metformin', 'Tablet', array['500 mg (hydrochloride)'], 'Hypoglycaemic agents'),
  ('Methadone', 'Concentrate for oral liquid', array['25 mg/5mL', '50 mg/5mL (hydrochloride)', '5 mg/mL', '10 mg/mL (hydrochloride)'], 'Opioid analgesics'),
  ('Methadone', 'Oral liquid', array['5 mg/5 mL', '10 mg/5 mL (hydrochloride)'], 'Opioid analgesics'),
  ('Methadone', 'Tablet', array['5 mg', '10 mg (hydrochloride)'], 'Opioid analgesics'),
  ('Methimazole', 'Tablet', array['5mg, 10mg', '5 mg', '10 mg'], 'Thyroid hormones and antithyroid medicines'),
  ('Methotrexate', 'Concentrated injection', array['1000 mg/10 mL'], 'Cytotoxic medicines'),
  ('Methotrexate', 'Injection', array['50 mg/2 mL'], 'Cytotoxic medicines'),
  ('Methotrexate', 'Powder for injection', array['50 mg (as sodium) in vial'], 'Cytotoxic medicines'),
  ('Methotrexate', 'Tablet', array['2.5 mg (as sodium)', '2.5 mg', '10 mg (as sodium)'], 'Cytotoxic medicines'),
  ('Methoxy polyethylene glycol-epoetin beta', null, '{}', 'Antianaemia medicines'),
  ('Methyldopa', 'Tablet', array['250 mg'], 'Antihypertensive medicines'),
  ('Methylergometrine', null, '{}', 'Uterotonics'),
  ('Methylprednisolone', 'Powder for injection', array['40 mg (as sodium succinate)', '125 mg (as sodium succinate) in vial'], 'Hormones and antihormones'),
  ('Metoclopramide', 'Injection', array['5 mg/mL (hydrochloride) in 2 mL ampoule'], 'Medicines for other common symptoms in palliative care'),
  ('Metoclopramide', 'Oral liquid', array['5 mg/5 mL'], 'Medicines for other common symptoms in palliative care'),
  ('Metoclopramide', 'Solid oral form', array['10 mg (hydrochloride)'], 'Medicines for other common symptoms in palliative care'),
  ('Metoclopramide', 'Tablet (scored)', array['10 mg (hydrochloride)'], 'Medicines for other common symptoms in palliative care'),
  ('Metoprolol', null, '{}', 'Antianginal medicines'),
  ('Metronidazole', 'Injection', array['500 mg in 100 mL vial'], 'Access group antibiotics'),
  ('Metronidazole', 'Oral liquid', array['200 mg/5 mL (as benzoate)'], 'Access group antibiotics'),
  ('Metronidazole', 'Suppository', array['500 mg', '1 g'], 'Access group antibiotics'),
  ('Metronidazole', 'Tablet', array['200 mg', '250 mg', '400 mg', '500 mg'], 'Access group antibiotics'),
  ('Micafungin', 'Powder for injection', array['50 mg (as sodium)', '100 mg (as sodium) in vial'], 'Antifungal medicines'),
  ('Midazolam', 'Injection', array['1 mg/mL in 5 mL vial', '5 mg/mL in 1 mL or 3 mL vial'], 'Preoperative medication and sedation for short-term procedures'),
  ('Midazolam', 'Oral liquid', array['2 mg/mL'], 'Preoperative medication and sedation for short-term procedures'),
  ('Midazolam', 'Solid oral dosage form', array['7.5 mg', '15 mg'], 'Preoperative medication and sedation for short-term procedures'),
  ('Midazolam', 'Solution for oromucosal administration', array['5 mg/mL in 0.5 mL, 1 mL, 1.5 mL, 2 mL pre-filled syringe', '10 mg/mL in 0.25 mL, 0.5 mL, 0.75 mL, 1 mL pre-filled syringe'], 'Preoperative medication and sedation for short-term procedures'),
  ('Miltefosine', 'Solid oral dosage form', array['10 mg', '50 mg'], 'Antileishmaniasis medicines'),
  ('Misoprostol', 'Tablet', array['200 micrograms'], 'Uterotonics'),
  ('Mometasone', null, '{}', 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Mometasone + formoterol', null, '{}', 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Morphine', 'Injection', array['1 mg/mL', '2 mg/mL', '10 mg/mL (sulfate or hydrochloride) in 1 mL ampoule'], 'Preoperative medication and sedation for short-term procedures'),
  ('Moxidectin', null, '{}', 'Antifilarials'),
  ('Moxifloxacin', 'Tablet', array['400 mg'], 'Antituberculosis medicines'),
  ('Moxifloxacin', 'Tablet (dispersible)', array['100 mg'], 'Antituberculosis medicines'),
  ('Multiple micronutrient powder', 'Sachets containing', '{}', 'Vitamins and minerals'),
  ('Multiple micronutrient supplement', 'Tablet containing', '{}', 'Other medicines administered to the mother'),
  ('Mupirocin', 'Cream', array['2% (as calcium)'], 'Anti-infective medicines'),
  ('Mupirocin', 'Ointment', array['2%'], 'Anti-infective medicines'),
  ('Nadroparin', null, '{}', 'Medicines affecting coagulation'),
  ('Naloxone', 'Injection', array['400 micrograms (hydrochloride) in 1 mL ampoule'], 'Specific'),
  ('Naltrexone', 'Injection suspension (extended-release)', array['380 mg in vial'], 'Medicines for alcohol use disorders'),
  ('Naltrexone', 'Tablet', array['50 mg'], 'Medicines for alcohol use disorders'),
  ('Naproxen', null, '{}', 'Medicines for headache disorders'),
  ('Natamycin', 'Suspension (eye drops)', array['5% âˆ’ Fungal keratitis ofloxacin'], 'Anti-infective agents'),
  ('Neostigmine', 'Injection', array['500 micrograms/mL (methylsulfate) in 1 mL ampoule', '2.5 mg/mL (methylsulfate) in 1 mL ampoule'], 'Medicines for myasthenia gravis'),
  ('Neostigmine', 'Tablet', array['15 mg (bromide)'], 'Medicines for myasthenia gravis'),
  ('Netilmicin', null, '{}', 'Anti-infective agents'),
  ('Nevirapine', 'Oral liquid', array['50 mg/5 mL'], 'Antiretrovirals'),
  ('Nevirapine', 'Tablet (dispersible)', array['50 mg', '200 mg'], 'Antiretrovirals'),
  ('Niclosamide', 'Tablet (chewable)', array['500 mg'], 'Intestinal anthelminthics'),
  ('Nifedipine', 'Immediate-release capsule', array['10 mg'], 'Antioxytocics (tocolytics)'),
  ('Nifurtimox', 'Tablet (scored)', array['30 mg', '120 mg'], 'Antitrypanosomal medicines'),
  ('Nilotinib', 'Capsule', array['150 mg', '200 mg'], 'Targeted therapies'),
  ('Nilutamide', null, '{}', 'Hormones and antihormones'),
  ('Nitrofurantoin', 'Oral liquid', array['25 mg/5 mL'], 'Access group antibiotics'),
  ('Nitrofurantoin', 'Solid oral dosage form', array['50 mg', '100 mg'], 'Access group antibiotics'),
  ('Nitrous oxide', 'Inhalation', '{}', 'Inhalational medicines'),
  ('Nivolumab', null, '{}', 'Immunomodulators'),
  ('Norethisterone', null, '{}', 'Progestogens'),
  ('Norethisterone enantate', 'Oily solution', array['200 mg/mL in 1 mL ampoule'], 'Injectable hormonal contraceptives'),
  ('Normal immunoglobulin', 'Intramuscular administration', array['16% protein solution'], 'Medicines for Guillain-BarrÃ© syndrome'),
  ('Normal immunoglobulin', 'Intravenous administration', array['5%', '10% protein solution'], 'Medicines for Guillain-BarrÃ© syndrome'),
  ('Normal immunoglobulin', 'Subcutaneous administration', array['15%', '16% protein solution'], 'Medicines for Guillain-BarrÃ© syndrome'),
  ('Nystatin', 'Lozenge', array['100 000 IU'], 'Antifungal medicines'),
  ('Nystatin', 'Oral liquid', array['100 000 IU/mL'], 'Antifungal medicines'),
  ('Nystatin', 'Pessary', array['100 000 IU'], 'Antifungal medicines'),
  ('Nystatin', 'Solid oral dosage form', array['500 000 IU'], 'Antifungal medicines'),
  ('Octreotide', 'Injection (immediate-release)', array['0.05 mg/mL', '0.1 mg/mL', '0.5 mg/mL (as acetate) in 1 mL vial'], 'Medicines for disorders of the pituitary hormone system'),
  ('Octreotide', 'Injection (modified-release)', array['20 mg (as acetate) in vial plus diluent'], 'Medicines for disorders of the pituitary hormone system'),
  ('Ofloxacin', null, '{}', 'Ear, nose and throat medicines'),
  ('Olanzapine', 'Powder for injection', array['10 mg in vial'], 'Medicines for psychotic disorders'),
  ('Ondansetron', 'Injection', array['2 mg/mL in 2 mL, 4 mL ampoule (as hydrochloride dihydrate)'], 'Medicines for other common symptoms in palliative care'),
  ('Ondansetron', 'Oral liquid', array['4 mg/5 mL (as hydrochloride dihydrate)'], 'Medicines for other common symptoms in palliative care'),
  ('Ondansetron', 'Solid oral dosage form', array['4 mg', '8 mg (as hydrochloride dihydrate)', '8 mg', '24 mg (as hydrochloride dihydrate)'], 'Medicines for other common symptoms in palliative care'),
  ('Oral rehydration salts â€“ zinc sulfate', 'Co-package containing', array['ORS powder for dilution (see Section 17.5.1) â€“ zinc sulfate tablet (dispersible, scored) 20 mg (see Section 17.5.2)'], 'Medicines used in diarrhoea'),
  ('Oseltamivir', 'Capsule', array['30 mg', '45 mg', '75 mg (as phosphate)'], 'Other antivirals'),
  ('Oseltamivir', 'Powder for oral liquid', array['6 mg/mL (as phosphate)'], 'Other antivirals'),
  ('Oxaliplatin', 'Injection', array['50 mg/10 mL in 10 mL vial', '100 mg/20 mL in 20 mL vial', '200 mg/40 mL in 40 mL vial'], 'Cytotoxic medicines'),
  ('Oxaliplatin', 'Powder for injection', array['50 mg', '100 mg in vial'], 'Cytotoxic medicines'),
  ('Oxamniquine', 'Capsule', array['250 mg'], 'Antischistosomals and other antitrematode medicines'),
  ('Oxamniquine', 'Oral liquid', array['250 mg/5 mL'], 'Antischistosomals and other antitrematode medicines'),
  ('Oxycodone', null, '{}', 'Opioid analgesics'),
  ('Oxygen', 'Inhalation', '{}', 'Inhalational medicines'),
  ('Oxygen', 'Inhalation (medical gas)', '{}', 'Inhalational medicines'),
  ('Oxytetracycline', null, '{}', 'Anti-infective agents'),
  ('Oxytocin', 'Injection', array['10 IU in 1 mL'], 'Uterotonics'),
  ('P-aminosalicylate sodium', 'Powder for oral solution', array['5.52 g in sachet (equivalent to 4 g p-aminosalicylic acid)'], 'Antituberculosis medicines'),
  ('Paclitaxel', 'Injection', array['6 mg/mL in vial'], 'Cytotoxic medicines'),
  ('Paliperidone', 'Injection (prolonged-release)', array['25 mg', '50 mg', '75 mg', '100 mg', '150 mg (as palmitate) in pre-filled syringe'], 'Medicines for psychotic disorders'),
  ('Palonosetron', null, '{}', 'Medicines for other common symptoms in palliative care'),
  ('Paracetamol (acetaminophen)', 'Oral liquid', array['120 mg/5 mL or 125 mg/5 mL, 250 mg/5 mL', '120 mg/5 mL or 125 mg/5 mL', '250 mg/5 mL'], 'Non-opioids and non-steroidal anti-inflammatory medicines (NSAIMs)'),
  ('Paromomycin', 'Solution for intramuscular injection', array['750 mg of paromomycin base (as sulfate)'], 'Antileishmaniasis medicines'),
  ('Paroxetine', null, '{}', 'Medicines for depressive disorders'),
  ('Penicillamine', 'Solid oral dosage form', array['250 mg'], 'Specific'),
  ('Pentamidine', 'Powder for injection', array['300 mg (as isetionate) in vial'], 'Antipneumocystosis and antitoxoplasmosis medicines'),
  ('Pentamidine', 'Tablet', array['200 mg', '300 mg (as isethionate)'], 'Antipneumocystosis and antitoxoplasmosis medicines'),
  ('Permethrin', 'Cream', array['5%'], 'Scabicides and pediculicides'),
  ('Permethrin', 'Lotion', array['1%'], 'Scabicides and pediculicides'),
  ('Phenobarbital', 'Injection', array['30 mg/mL or 60 mg/mL , 200 mg/mL (sodium)'], 'Antiseizure medicines'),
  ('Phenobarbital', 'Oral liquid', array['15 mg/5 mL'], 'Antiseizure medicines'),
  ('Phenobarbital', 'Tablet', array['15 mg', '30 mg', '60 mg', '100 mg'], 'Antiseizure medicines'),
  ('Phenoxymethylpenicillin', 'Powder for oral liquid', array['250 mg/5 mL (as potassium)'], 'Access group antibiotics'),
  ('Phenoxymethylpenicillin', 'Solid oral dosage form', array['250 mg', '500 mg (as potassium)'], 'Access group antibiotics'),
  ('Phenytoin', 'Injection', array['50 mg/mL (phenytoin sodium)'], 'Antiseizure medicines'),
  ('Phenytoin', 'Oral liquid', array['30 mg/5 mL (phenytoin)'], 'Antiseizure medicines'),
  ('Phenytoin', 'Solid oral dosage form', array['25 mg', '50 mg', '100 mg (phenytoin sodium)'], 'Antiseizure medicines'),
  ('Phenytoin', 'Tablet (chewable)', array['50 mg (phenytoin)'], 'Antiseizure medicines'),
  ('Phytomenadione', 'Injection', array['1 mg/0.5mL', '1 mg/mL', '10 mg/mL in ampoule'], 'Medicines affecting coagulation'),
  ('Phytomenadione', 'Injection (mixed micelle solution)', array['2 mg/0.2 mL', '10 mg/mL in ampoule'], 'Medicines affecting coagulation'),
  ('Phytomenadione', 'Tablet', array['5 mg'], 'Medicines affecting coagulation'),
  ('Pilocarpine', 'Solution (eye drops)', array['2%', '4% (hydrochloride or nitrate)'], 'Miotics and antiglaucoma medicines'),
  ('Piperacillin + tazobactam', 'Powder for injection', array['2 g (as sodium) + 250 mg (as sodium)', '4 g (as sodium) + 500 mg (as sodium) in vial'], 'Watch group antibiotics'),
  ('Plazomicin', 'Injection', array['500 mg/10 mL'], 'Reserve group antibiotics'),
  ('Podophyllotoxin', null, '{}', 'Medicines affecting skin differentiation and proliferation'),
  ('Podophyllum resin', 'Solution', array['10% to 25%'], 'Medicines affecting skin differentiation and proliferation'),
  ('Polygeline injectable solution 3.5%', null, '{}', 'Plasma substitutes'),
  ('Polymyxin B', 'Powder for injection', array['500 000 IU (equivalent to 50 mg polymyxin B base) in vial'], 'Reserve group antibiotics'),
  ('Poractant alfa', 'Suspension for intratracheal instillation', array['80 mg/mL'], 'Medicines administered to the neonate [c]'),
  ('Potassium chloride', 'Solution', array['11.2% in 20 mL ampoule (equivalent to K + 1.5 mmol/mL, Cl â€“ 1.5 mmol/mL)'], 'Parenteral'),
  ('Potassium chloride', 'Solution for dilution', array['7.5% (equivalent to K + 1 mmol/mL and Cl â€“ 1 mmol/mL)', '15% (equivalent to K + 2 mmol/mL and Cl â€“ 2 mmol/mL)'], 'Parenteral'),
  ('Potassium iodide', 'Tablet (scored)', array['65 mg'], 'Thyroid hormones and antithyroid medicines'),
  ('Potassium permanganate', 'Aqueous solution', array['1:10 000'], 'Anti-infective medicines'),
  ('Povidone iodine', 'Solution', array['10% (equivalent to 1% available iodine)'], 'Antiseptics'),
  ('Pravastatin', null, '{}', 'Lipid-lowering agents'),
  ('Praziquantel', 'Tablet', array['150 mg, 500 mg'], 'Intestinal anthelminthics'),
  ('Praziquantel', 'Tablet (scored)', array['600 mg'], 'Intestinal anthelminthics'),
  ('Precipitated sulfur topical ointment', null, '{}', 'Scabicides and pediculicides'),
  ('Prednisolone', 'Oral liquid', array['5 mg/mL', '1 mg/mL'], 'Antiallergics and medicines used in anaphylaxis'),
  ('Prednisolone', 'Retention enema', array['20 mg/100 mL (as sodium phosphate)'], 'Antiallergics and medicines used in anaphylaxis'),
  ('Prednisolone', 'Solution (eye drops)', array['0.5% (sodium phosphate)'], 'Antiallergics and medicines used in anaphylaxis'),
  ('Prednisolone', 'Tablet', array['5 mg', '25 mg', '1 mg', '10 mg'], 'Antiallergics and medicines used in anaphylaxis'),
  ('Prednisone', null, '{}', 'Antiallergics and medicines used in anaphylaxis'),
  ('Pretomanid', 'Tablet', array['200 mg'], 'Antituberculosis medicines'),
  ('Primaquine', 'Tablet', array['7.5 mg', '15 mg (as phosphate)'], 'Antimalarial medicines'),
  ('Procaine benzylpenicillin', 'Powder for injection', array['1 g (=1 million IU)', '3 g (=3 million IU) in vial'], 'Access group antibiotics'),
  ('Procarbazine', 'Capsule', array['50 mg (as hydrochloride)'], 'Cytotoxic medicines'),
  ('Progesterone vaginal ring', 'Progesterone-releasing vaginal ring', array['containing 2.074 g of micronized progesterone'], 'Intravaginal contraceptives'),
  ('Propanol', null, '{}', 'Antiseptics'),
  ('Propofol', 'Injection', array['10 mg/mL', '20 mg/mL'], 'Injectable medicines'),
  ('Propranolol', 'Tablet', array['10 mg', '40 mg (hydrochloride)'], 'Medicines for headache disorders'),
  ('Propylthiouracil', 'Tablet', array['50 mg'], 'Thyroid hormones and antithyroid medicines'),
  ('Protamine sulfate', 'Injection', array['10 mg/mL in 5 mL ampoule or vial'], 'Medicines affecting coagulation'),
  ('Protionamide', null, '{}', 'Antituberculosis medicines'),
  ('Pyrantel', 'Tablet (chewable)', array['250 mg (as embonate or pamoate)'], 'Intestinal anthelminthics'),
  ('Pyrazinamide', 'Tablet', array['400 mg', '500 mg Tablet (dispersible): 150 mg'], 'Antituberculosis medicines'),
  ('Pyridostigmine', 'Injection', array['5 mg/mL (bromide) in ampoule or vial'], 'Medicines for myasthenia gravis'),
  ('Pyridostigmine', 'Tablet (scored)', array['60 mg (bromide)'], 'Medicines for myasthenia gravis'),
  ('Pyridoxine', 'Tablet', array['10 mg', '25 mg (hydrochloride)'], 'Vitamins and minerals'),
  ('Pyrimethamine', 'Tablet', array['25 mg'], 'Antipneumocystosis and antitoxoplasmosis medicines'),
  ('Quetiapine', 'Tablet (immediate-release)', array['25 mg', '100 mg', '150 mg', '200 mg', '300 mg'], 'Medicines for psychotic disorders'),
  ('Quetiapine', 'Tablet (modified-release)', array['50 mg', '150 mg', '200 mg', '300 mg', '400 mg'], 'Medicines for psychotic disorders'),
  ('Quinine', 'Solution for infusion', array['60 mg/mL', '300 mg/mL (hydrochloride) in 2 mL ampoule'], 'Antimalarial medicines'),
  ('Raltegravir', 'Granules for oral suspension', array['100 mg in sachet'], 'Antiretrovirals'),
  ('Raltegravir', 'Tablet', array['400 mg'], 'Antiretrovirals'),
  ('Raltegravir', 'Tablet (chewable)', array['25 mg'], 'Antiretrovirals'),
  ('Rasburicase', 'Powder and solvent for solution for infusion', array['1.5 mg (with 1 mL solvent)', '7.5 mg (with 5 mL solvent) in vial'], 'Supportive medicines'),
  ('Ravidasvir', 'Tablet', array['200 mg'], 'Antihepatitis medicines'),
  ('Realgar-Indigo naturalis formulation', 'Tablet', array['270 mg (containing tetra-arsenic tetra-sulfide 30 mg)'], 'Cytotoxic medicines'),
  ('Retinol', 'Oral liquid', array['100 000 IU/mL (as palmitate)'], 'Vitamins and minerals'),
  ('Retinol', 'Soft capsule', array['50 000 IU', '100 000 IU', '200 000 IU (as acetate or palmitate)'], 'Vitamins and minerals'),
  ('Retinol', 'Water-miscible injection', array['50 000 IU/mL (as palmitate) in 2 mL ampoule or vial'], 'Vitamins and minerals'),
  ('Ribavirin', 'Injection for intravenous administration', array['800 mg', '1 g in 10 mL phosphate buffer solution'], 'Antihepatitis medicines'),
  ('Ribavirin', 'Solid oral dosage form', array['200 mg', '400 mg', '600 mg'], 'Antihepatitis medicines'),
  ('Riboflavin', 'Tablet', array['5 mg'], 'Vitamins and minerals'),
  ('Rifabutin', 'Solid oral dosage form', array['150 mg. rifampicin Oral liquid: 20 mg/mL', '150 mg', '300 mg'], 'Antituberculosis medicines'),
  ('Rifampicin', 'Oral liquid', array['20 mg/mL'], 'Antileprosy medicines'),
  ('Rifampicin', 'Solid oral dosage form', array['150 mg', '300 mg'], 'Antileprosy medicines'),
  ('Rifapentine', 'Tablet', array['150 mg', '300 mg'], 'Antituberculosis medicines'),
  ('Rifapentine', 'Tablet (dispersible, scored)', array['150 mg'], 'Antituberculosis medicines'),
  ('Risperidone', 'Solid oral dosage form', array['0.25 mg to 6.0 mg'], 'Medicines for psychotic disorders'),
  ('Ritonavir', 'Tablet (heat stable)', array['25 mg', '100 mg'], 'Antiretrovirals'),
  ('Rivaroxaban', null, '{}', 'Medicines affecting coagulation'),
  ('Salbutamol', 'Injection', array['500 micrograms/mL (as sulfate) in 1 mL, 5 mL ampoule'], 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Salbutamol', 'Solution for inhalation', array['100 micrograms (as sulfate) per actuation in pressurized metered-dose inhaler', '2.5 mg/2.5 mL', '5 mg/2.5 mL (as sulfate) in 2.5 mL single-dose ampoules for use in nebulizers', '5 mg/mL (as sulfate) in multi-dose bottle for use in nebulizers'], 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Salicylic acid', 'Solution', array['5%'], 'Medicines affecting skin differentiation and proliferation'),
  ('Selenium sulfide', 'Detergent-based suspension', array['2%'], 'Antifungal medicines'),
  ('Senna', 'Oral liquid', array['7.5 mg/5 mL'], 'Medicines for other common symptoms in palliative care'),
  ('Senna', 'Tablet', array['7.5 mg (sennosides) (or traditional dosage forms)'], 'Medicines for other common symptoms in palliative care'),
  ('Sertraline', null, '{}', 'Medicines for depressive disorders'),
  ('Sevoflurane', 'Inhalation', '{}', 'Inhalational medicines'),
  ('Silver diamine fluoride', 'Solution', array['38% w/v'], 'Dental medicines and preparations'),
  ('Silver sulfadiazine', 'Cream', array['1%'], 'Anti-infective medicines'),
  ('Simvastatin', 'Tablet', array['5 mg', '10 mg', '20 mg', '40 mg'], 'Lipid-lowering agents'),
  ('Sodium calcium edetate', 'Injection', array['200 mg/mL in 5 mL ampoule'], 'Specific'),
  ('Sodium chloride', 'Injectable solution', array['0.9% isotonic (equivalent to Na + 154 mmol/L, Cl â€“ 154 mmol/L)'], 'Parenteral'),
  ('Sodium hydrogen carbonate', 'Injectable solution', array['1.4% isotonic (equivalent to Na + 167 mmol/L, HCO3 â€“ 167 mmol/L)'], 'Parenteral'),
  ('Sodium hydrogen carbonate', 'Solution', array['8.4% in 10 mL ampoule (equivalent to Na + 1000 mmol/L, HCO3 â€“ 1000 mmol/L)'], 'Parenteral'),
  ('Sodium nitrite', 'Injection', array['30 mg/mL in 10 mL ampoule'], 'Specific'),
  ('Sodium nitroprusside', 'Powder for infusion', array['50 mg in ampoule'], 'Antihypertensive medicines'),
  ('Sodium stibogluconate', 'Injection', array['100 mg/mL in 30 mL vial'], 'Antileishmaniasis medicines'),
  ('Sodium thiosulfate', 'Injection', array['250 mg/mL in 50 mL ampoule'], 'Specific'),
  ('Sodium thiosulfate', 'Solution', array['15%'], 'Specific'),
  ('Sofosbuvir', 'Granules', array['200 mg in sachet'], 'Antihepatitis medicines'),
  ('Sofosbuvir', 'Tablet', array['200 mg', '400 mg'], 'Antihepatitis medicines'),
  ('Sofosbuvir + velpatasvir', 'Granules', array['150 mg + 37.5 mg', '200 mg + 50 mg in sachet'], 'Antihepatitis medicines'),
  ('Sofosbuvir + velpatasvir', 'Tablet', array['200 mg + 50 mg', '400 mg + 100 mg'], 'Antihepatitis medicines'),
  ('Spectinomycin', 'Powder for injection', array['2 g (as hydrochloride) in vial'], 'Access group antibiotics'),
  ('Spironolactone', 'Oral liquid', array['25 mg/5 mL'], 'Medicines used in heart failure'),
  ('Spironolactone', 'Tablet', array['25 mg', '12.5 mg'], 'Medicines used in heart failure'),
  ('Streptokinase', 'Powder for injection', array['1.5 million IU in vial'], 'Thrombolytic medicines'),
  ('Streptomycin', 'Powder for injection', array['1 g (as sulfate) in vial'], 'Antituberculosis medicines'),
  ('Succimer', 'Solid oral dosage form', array['100 mg'], 'Specific'),
  ('Sulfadiazine', 'Tablet', array['500 mg'], 'Antipneumocystosis and antitoxoplasmosis medicines'),
  ('Sulfadoxine + pyrimethamine', 'Tablet (dispersible)', array['250 mg + 12.5 mg', '500 mg + 25 mg'], 'Antimalarial medicines'),
  ('Sulfamethoxazole + trimethoprim', 'Injection', array['80 mg + 16 mg/mL in 5 mL ampoule', '80 mg + 16 mg/mL in 10 mL ampoule'], 'Antipneumocystosis and antitoxoplasmosis medicines'),
  ('Sulfamethoxazole + trimethoprim', 'Oral liquid', array['200 mg + 40 mg/5 mL'], 'Antipneumocystosis and antitoxoplasmosis medicines'),
  ('Sulfamethoxazole + trimethoprim', 'Tablet', array['100 mg + 20 mg', '400 mg + 80 mg', '800 mg + 160 mg'], 'Antipneumocystosis and antitoxoplasmosis medicines'),
  ('Sulfamethoxazole + trimethoprim', 'Tablet (dispersible)', array['100 mg + 20 mg'], 'Antipneumocystosis and antitoxoplasmosis medicines'),
  ('Sulfasalazine', 'Retention enema', array['3 g/100 mL'], 'Anti-inflammatory medicines'),
  ('Sulfasalazine', 'Suppository', array['500 mg'], 'Anti-inflammatory medicines'),
  ('Sulfasalazine', 'Tablet', array['500 mg'], 'Anti-inflammatory medicines'),
  ('Sumatriptan', 'Injection (subcutaneous)', array['6 mg/ 0.5 mL in pre-filled syringe or pen'], 'Medicines for headache disorders'),
  ('Sumatriptan', 'Tablet', array['50 mg'], 'Medicines for headache disorders'),
  ('Sunscreen, broad-spectrum', 'Topical', '{}', 'Sunscreens'),
  ('Suramin sodium', 'Powder for injection', array['1 g in vial'], 'Antitrypanosomal medicines'),
  ('Suxamethonium', 'Injection', array['50 mg/mL (chloride) in 2 mL ampoule'], 'Muscle relaxants (peripherally-acting) and cholinesterase inhibitors'),
  ('Tacalcitol', null, '{}', 'Medicines affecting skin differentiation and proliferation'),
  ('Tacrolimus', 'Capsule (immediate-release)', array['0.5 mg', '0.75 mg', '1 mg', '2 mg', '5 mg'], 'Immunomodulators for non-malignant disease'),
  ('Tacrolimus', 'Granules for oral supsension', array['0.2 mg', '1 mg'], 'Immunomodulators for non-malignant disease'),
  ('Tacrolimus', 'Injection', array['5 mg/mL in 1 mL vial'], 'Immunomodulators for non-malignant disease'),
  ('Tamoxifen', 'Tablet', array['10 mg', '20 mg (as citrate)'], 'Hormones and antihormones'),
  ('Tedizolid phosphate', null, '{}', 'Reserve group antibiotics'),
  ('Tenofovir disoproxil fumarate', 'Tablet', array['300 mg (tenofovir disoproxil fumarate â€“ equivalent to 245 mg tenofovir disoproxil)'], 'Antiretrovirals'),
  ('Terbinafine', 'Cream or ointment', array['1% (hydrochloride)'], 'Antifungal medicines'),
  ('Terbutaline', null, '{}', 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Terizidone', null, '{}', 'Antituberculosis medicines'),
  ('Testosterone', 'Injection', array['200 mg (enanthate) in 1 mL ampoule'], 'Androgens'),
  ('Tetracycline', 'Eye ointment', array['1% (hydrochloride)'], 'Anti-infective agents'),
  ('Thalidomide', 'Capsule', array['50 mg'], 'Immunomodulators'),
  ('Thiamine', 'Injection', array['50 mg/mL (hydrochloride) in ampoule or vial'], 'Vitamins and minerals'),
  ('Thiamine', 'Tablet', array['50 mg (hydrochloride)'], 'Vitamins and minerals'),
  ('Thiopental', null, '{}', 'Injectable medicines'),
  ('Tinidazole', null, '{}', 'Antiamoebic and antigiardiasis medicines'),
  ('Tioguanine', 'Solid oral dosage form', array['40 mg'], 'Cytotoxic medicines'),
  ('Tiotropium', 'Powder for inhalaton', array['18 micrograms in capsule'], 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Tiotropium', 'Solution for inhalation', array['1.25 micrograms', '2.5 micrograms per actuation in soft mist inhaler'], 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Tirzepatide', null, '{}', 'Hypoglycaemic agents'),
  ('Tobramycin', null, '{}', 'Anti-infective agents'),
  ('Torasemide', null, '{}', 'Medicines used in heart failure'),
  ('Tranexamic acid', 'Injection', array['100 mg/mL in 10 mL ampoule'], 'Medicines affecting coagulation'),
  ('Triamcinolone acetonide', null, '{}', 'Medicines for juvenile joint diseases'),
  ('Triamcinolone hexacetonide', 'Injection', array['20 mg/mL in vial'], 'Medicines for juvenile joint diseases'),
  ('Triclabendazole', 'Tablet (scored)', array['250 mg'], 'Antischistosomals and other antitrematode medicines'),
  ('Trimethoprim', 'Injection', array['80 mg + 16 mg/mL in 5 mL ampoule', '80 mg + 16 mg/mL in 10 mL ampoule'], 'Access group antibiotics'),
  ('Trimethoprim', 'Oral liquid', array['200 mg + 40 mg/5 mL', '50 mg/5 mL'], 'Access group antibiotics'),
  ('Trimethoprim', 'Tablet', array['100 mg + 20 mg', '400 mg + 80 mg', '800 mg + 160 mg', '100 mg', '200 mg'], 'Access group antibiotics'),
  ('Trimethoprim', 'Tablet (dispersible)', array['100 mg + 20 mg'], 'Access group antibiotics'),
  ('Trimethoprim', 'Tablet (scored)', array['300 mg + 25 mg + 800 mg + 160 mg'], 'Access group antibiotics'),
  ('Triptorelin', null, '{}', 'Hormones and antihormones'),
  ('Tropicamide', 'Eye drops', array['0.5%'], 'Ophthalmic medicines'),
  ('Tropisetron', null, '{}', 'Medicines for other common symptoms in palliative care'),
  ('Ulipristal', 'Tablet', array['30 mg (as acetate)'], 'Oral hormonal contraceptives'),
  ('Umeclidinium', null, '{}', 'Antiasthmatic medicines and medicines for chronic obstructive pulmonary disease'),
  ('Urea', 'Cream', array['5%'], 'Medicines affecting skin differentiation and proliferation'),
  ('Urea', 'Cream or ointment', array['5%', '10%'], 'Medicines affecting skin differentiation and proliferation'),
  ('Valaciclovir (oral)', null, '{}', 'Medicines for central nervous system infections'),
  ('Valganciclovir', 'Powder for oral solution', array['50 mg/mL (as hydrochloride)'], 'Other antivirals'),
  ('Valganciclovir', 'Tablet', array['450 mg (as hydrochloride)'], 'Other antivirals'),
  ('Vancomycin', 'Capsule', array['125 mg', '250 mg (as hydrochloride)'], 'Watch group antibiotics'),
  ('Vancomycin', 'Powder for injection', array['250 mg', '500 mg', '1 g (as hydrochloride) in vial'], 'Watch group antibiotics'),
  ('Varenicline', 'Tablet', array['0.5 mg, 1 mg'], 'Medicines for nicotine use disorders'),
  ('Vecuronium', 'Powder for injection', array['10 mg (bromide) in vial'], 'Muscle relaxants (peripherally-acting) and cholinesterase inhibitors'),
  ('Verapamil', 'Injection', array['2.5 mg/mL (hydrochloride) in 2 mL ampoule'], 'Medicines for headache disorders'),
  ('Verapamil', 'Tablet', array['40 mg', '80 mg (hydrochloride)'], 'Medicines for headache disorders'),
  ('Verapamil', 'Tablet (extended-release)', array['120 mg', '180 mg', '240 mg'], 'Medicines for headache disorders'),
  ('Verapamil', 'Tablet (immediate-release)', array['40 mg', '80 mg', '120 mg'], 'Medicines for headache disorders'),
  ('Vinblastine', 'Injection', array['10 mg/10 mL (sulfate) in vial'], 'Cytotoxic medicines'),
  ('Vinblastine', 'Powder for injection', array['10 mg (sulfate) in vial'], 'Cytotoxic medicines'),
  ('Vincristine', 'Injection', array['1 mg/mL (sulfate)', '2 mg/2 mL (sulfate) in vial'], 'Cytotoxic medicines'),
  ('Vincristine', 'Powder for injection', array['1 mg', '5 mg (sulfate) in vial'], 'Cytotoxic medicines'),
  ('Vinorelbine', 'Capsule', array['20 mg', '30 mg', '80 mg'], 'Cytotoxic medicines'),
  ('Vinorelbine', 'Injection', array['10 mg/mL in 1 mL, 5 mL vial'], 'Cytotoxic medicines'),
  ('Voriconazole', 'Tablet', array['50 mg', '200 mg Powder for injection: 200 mg in vial Powder for oral liquid: 40 mg/mL'], 'Antifungal medicines'),
  ('Warfarin', 'Tablet (scored)', array['1 mg', '2 mg', '3 mg', '5 mg (sodium)', '0.5 mg'], 'Medicines affecting coagulation'),
  ('Xylometazoline', 'Nasal drops', array['0.05%'], 'Ear, nose and throat medicines'),
  ('Xylometazoline', 'Nasal spray', array['0.05%'], 'Ear, nose and throat medicines'),
  ('Zanubrutinib', null, '{}', 'Targeted therapies'),
  ('Zidovudine', 'Capsule', array['250 mg'], 'Antiretrovirals'),
  ('Zidovudine', 'Oral liquid', array['50 mg/5 mL'], 'Antiretrovirals'),
  ('Zidovudine', 'Solution for IV infusion', array['10 mg/mL in 20 mL vial'], 'Antiretrovirals'),
  ('Zidovudine', 'Tablet', array['300 mg'], 'Antiretrovirals'),
  ('Zinc sulfate', 'Tablet (dispersible, scored)', array['20 mg'], 'Medicines for diarrhoea'),
  ('Zoledronic acid', 'Concentrate solution for infusion', array['4 mg/5 mL in 5 mL vial'], 'Supportive medicines'),
  ('Zoledronic acid', 'Solution for infusion', array['4 mg/100 mL in 100 mL bottle'], 'Supportive medicines'),
  ('Zuclopenthixol decanoate', null, '{}', 'Medicines for psychotic disorders')
on conflict (name, coalesce(form, '')) do nothing;
